# -*- coding: utf-8 -*-
"""practice11_Github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rU0bIl_r0KI0FZ4cFsa6Mfu-mIwj6eXE
"""

print("hello world")